### ISSUE TITLE
Bug when register two shortcut

### ISSUE THREAD

**Issue by Aoi-hosizora** [ddqd/qxtglobalshortcut5#3]
I use Qt5.5.1 for MSVC 2010. There are 4 situations when register and unregister two shortcut in sequence.

For example `Ctrl+A`(s1) and `Ctrl+B`(s2):
+ register s1 -> register s2 -> unregister s2 -> unregister s1 (normal)
+ register s1 -> register s2 -> unregister s1 -> (s2 could not work)
+ register s2 -> register s1 -> unregister s1 -> unregister s2 (normal)
+ register s2 -> register s1 -> unregister s2 -> (s1 could not work)

There is a bug when I unregister the first shortcut after register the second shortcut.

Some of my connect and disconnect code:

```c++
// register
QxtGlobalShortcut *s1= new QxtGlobalShortcut(QKeySequence(QObject::tr("down")), this);
connect(s1, &QxtGlobalShortcut::activated, [=]() {
    mouse_event(MOUSEEVENTF_WHEEL, 0, 0, WHEEL_DELTA, 0);
});

// unregister
s1.disconnect();
```

**Comment by StephenArk30** [comment]
To whom still using qxtglobalshortcut (@Aoi-hosizora if you still need it):

First of all, do not use qxtglobalshortcut any longer. LIBQXT IS NO LONGER MAINTAINED, and [QShortcut](https://doc.qt.io/qt-5/qshortcut.html) is good.

If you need to use qxt for some reason, you may have this issue because qxt will only `installNativeEventFilter` on the first QxtGlobalShortcutPrivate(see [here](https://github.com/ddqd/qxtglobalshortcut5/blob/1ead85a849db58cfb51cac92910fdbcf0ac69f1a/gui/qxtglobalshortcut.cpp#L51)) which is constructed by QxtGlobalShortcut. So when you destroy the first QxtGlobalShortcut, you destroy the instance with the event filter too. Without the event filter, you cannot capture the hotkey event, and the other shortcuts will break.

The solution is simple: create an empty shortcut, and never delete it (unless you are going to delete all shortcuts). Or you can modify the code of the library, adding a static instance. For example:

```cpp
QxtGlobalShortcutPrivate::QxtGlobalShortcutPrivate(bool isStatic) : enabled(true), key(Qt::Key(0)), mods(Qt::NoModifier)
{
    if (!isStatic) {
        if (ref == 0) {
            // ...
            eventInstance = new QxtGlobalShortcutPrivate(true); // eventInstance is static
            QAbstractEventDispatcher::instance()->installNativeEventFilter(getEventInstance());
        }
        ++ref;
    }
}

QxtGlobalShortcutPrivate::~QxtGlobalShortcutPrivate()
{
    --ref;
    if (ref == 0) {
        QAbstractEventDispatcher *ed = QAbstractEventDispatcher::instance();
        if (ed != 0) {
            ed->removeNativeEventFilter(eventInstance);
            delete eventInstance;
            eventInstance = nullptr;
        }
    }
    if (ref < 0) ref = 0; // when deleting eventInstance, ref is -1
}
```

**Comment by Aoi-hosizora** [comment]
Oh I see. Thx :P
Now I have changed to use Windows' native methods (`RegisterHotKey`, `nativeEvent`, etc.) and `QKeySequence` using https://github.com/ddqd/qxtglobalshortcut5/blob/master/gui/qxtglobalshortcut_win.cpp :)
